openapi: 3.0.0
info:
  version: 1.0.0
  title: Api de recette
  description: Api pour gérer des recettes de tous genre
  
servers: 
  - url: http://localhost/serviceWebFinal.Api
paths:
  /recipes:
    get:
      tags:
        - Recette
      summary: Obtenir tous les recettes
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/definitions/Recipe"
  /recipes?id={id}:
    get:
      tags:
        - Recette
      summary: Obtenir un recette particuliaire
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/definitions/RecipeExtend"
      parameters:
        - name: "Id"
          in: "path"
          description: "Le Id de la recette à selectionner. "
          required: true
          type: "number"
  /recipe:
    post:
      tags:
      - "Recette"
      summary: "Ajouter une nouvelle recette"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "La liste des informations de la recette"
        required: true
        schema:
          $ref: "#/definitions/RecipeExtend"
      responses:
        "405":
          description: "Information invalide"
          content:
            application/json:
              schema:
                $ref: "#/definitions/OperationResultError"
        "201":
          description: "Recette créer"
          content:
            application/json:
              schema:
                $ref: "#/definitions/OperationResult"
  /recipe/{id}:
    post:
      tags:
      - "Recette"
      summary: "Modifier une recette"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "Id"
        description: "Le Id de la recette à selectionner. "
        required: true
        type: "number"    

      - in: "body"
        name: "body"
        description: "La liste des informations de la recette"
        required: true
        schema:
          $ref: "#/definitions/RecipeExtend"
      responses:
        "500":
          description: "Information invalide"
          content:
            application/json:
              schema:
                $ref: "#/definitions/OperationResultError" 
        "200":
          description: "Recette as bien été modifiée"
          content:
            application/json:
              schema:
                $ref: "#/definitions/OperationResult" 
    delete:
      tags:
      - "Recette"
      summary: "Supprimer une recette"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "Id"
        description: "Le Id de la recette à selectionner. "
        required: true
        type: "number"  
      responses:
        '200':
          description: "Recette bien supprimée"
          content:
            application/json:
              schema:
                $ref: "#/definitions/OperationResult"  
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/definitions/OperationResultError" 
  /recipe-type:
    get:
      tags:
        - Type de recette
      summary: Obtenir tous les types de recette
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/definitions/RecipeType"

definitions:
  RecipeType:
    type: "object"
    properties:
      Id:
        type: "integer"
        format: "int32"
      Name:
        type: "string"
    xml:
      name: "RecipeType"
  Recipe:
    type: "object"
    properties:
      Id:
        type: "integer"
        format: "int32"
      Name:
        type: "string"
      TypeName:
        type: "string"
      TimeCook:
        type: "integer"
        format: "int32"
      TimePrep:
        type: "integer"
        format: "int32"
      Instructions:
        type: "string"
      Ingredients:
        type: "string"
      Note:
        type: "string"
      Tags:
        type: "string"
    xml:
      name: "Recipe"

  RecipeExtend:
    required:
    - "name"
    - "Type"
    - "TimeCook"
    - "TimePrep"
    - "Instructions"
    - "Ingredients"
    type: "object"
    properties:
      Id:
        type: "integer"
        format: "int32"
      Name:
        type: "string"
      Type:
        type: "integer"
        format: "int32"
      TimeCook:
        type: "integer"
        format: "int32"
      TimePrep:
        type: "integer"
        format: "int32"
      Instructions:
        type: "string"
      Ingredients:
        type: "string"
      Note:
        type: "string"
      Tags:
        type: "string"
    xml:
      name: "RecipeExtend"

  OperationResult:
    type: "object"
    properties:
      success:
        type: "boolean"
        default: true
      Message:
        type: "string"
    xml:
      name: "OperationResult"

  OperationResultError:
    type: "object"
    properties:
      success:
        type: "boolean"
        default: false
      Message:
        type: "string"
    xml:
      name: "OperationResultError"